In [1]:
import pandas as pd

In [4]:
def my_function():
    # indent 4 spaces
    pass

In [7]:
def my_sq(x):
    """Squares a given value
    
    parameters
    ----------
    x: number to square
    
    returns
    -------
    squared number
    """
    return x ** 2

In [10]:
?my_sq

Signature: my_sq(x)
Docstring:
Squares a given value

parameters
----------
x: number to square

returns
-------
squared number
File:      c:\users\danie\desktop\2018-10-python1\notebooks\<ipython-input-7-07857fbf087d>
Type:      function


In [11]:
my_sq(4)

16

In [12]:
def avg_2(x, y):
    """calculates the average between 2 numbers
    """
    return (x + y) / 2

In [17]:
avg_2(10, 20)

15.0

In [19]:
df = pd.DataFrame({
    'a': [10, 20, 30],
    'b': [20, 30, 40]
})
df

a   b
0  10  20
1  20  30
2  30  40

In [21]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [22]:
df['a'].apply(my_sq)
#df['asq'] = df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [31]:
def my_exp(x, pizza):
    """Raise x to the e power
    """
    return x ** pizza

In [32]:
my_exp(2, 10)

1024

In [33]:
df['a'].apply(my_exp, pizza=2)

0    100
1    400
2    900
Name: a, dtype: int64

In [34]:
df['a'].apply(my_exp, pizza=3)

0     1000
1     8000
2    27000
Name: a, dtype: int64

In [35]:
df

a   b
0  10  20
1  20  30
2  30  40

In [36]:
def print_me(x):
    print(x)

In [37]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [38]:
df['a']

0    10
1    20
2    30
Name: a, dtype: int64

In [40]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [41]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [48]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [43]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [45]:
df.apply(avg_3_apply, axis=1)

IndexError: ('index out of bounds', 'occurred at index 0')

In [49]:
def avg_2_apply(row):
    x = row[0]
    y = row[1]
    return (x + y) / 2

In [50]:
df.apply(avg_2_apply, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [51]:
import seaborn as sns

In [52]:
titanic = sns.load_dataset('titanic')

In [53]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [54]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
survived       891 non-null int64
pclass         891 non-null int64
sex            891 non-null object
age            714 non-null float64
sibsp          891 non-null int64
parch          891 non-null int64
fare           891 non-null float64
embarked       889 non-null object
class          891 non-null category
who            891 non-null object
adult_male     891 non-null bool
deck           203 non-null category
embark_town    889 non-null object
alive          891 non-null object
alone          891 non-null bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [56]:
import numpy as np
def count_missing(vec):
    null_vec = pd.isnull(vec) # vector of T/F
    null_count = np.sum(null_vec)
    return null_count
    # return np.sum(null_vec)

In [58]:
titanic.apply(count_missing)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [59]:
titanic.apply(count_missing, axis=1)

0      1
1      0
2      1
3      0
4      1
5      2
6      0
7      1
8      1
9      1
10     0
11     0
12     1
13     1
14     1
15     1
16     1
17     2
18     1
19     2
20     1
21     0
22     1
23     0
24     1
25     1
26     2
27     0
28     2
29     2
      ..
861    1
862    0
863    2
864    1
865    1
866    1
867    0
868    2
869    1
870    1
871    0
872    0
873    1
874    1
875    1
876    1
877    1
878    2
879    0
880    1
881    1
882    1
883    1
884    1
885    1
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [60]:
titanic.loc[pd.isnull(titanic['embark_town'])]

survived  pclass     sex   age  sibsp  parch  fare embarked  class  \
61          1       1  female  38.0      0      0  80.0      NaN  First   
829         1       1  female  62.0      0      0  80.0      NaN  First   

       who  adult_male deck embark_town alive  alone  
61   woman       False    B         NaN   yes   True  
829  woman       False    B         NaN   yes   True

In [61]:
row_missing_counts = titanic.apply(count_missing, axis=1)

In [64]:
titanic['num_missing'] = row_missing_counts

In [62]:
row_missing_counts.value_counts()

1    549
0    182
2    160
dtype: int64

In [69]:
titanic.loc[titanic['num_missing'] > 1].sample(10)

survived  pclass     sex  age  sibsp  parch     fare embarked  class  \
826         0       3    male  NaN      0      0  56.4958        S  Third   
739         0       3    male  NaN      0      0   7.8958        S  Third   
495         0       3    male  NaN      0      0  14.4583        C  Third   
223         0       3    male  NaN      0      0   7.8958        S  Third   
5           0       3    male  NaN      0      0   8.4583        Q  Third   
388         0       3    male  NaN      0      0   7.7292        Q  Third   
301         1       3    male  NaN      2      0  23.2500        Q  Third   
863         0       3  female  NaN      8      2  69.5500        S  Third   
107         1       3    male  NaN      0      0   7.7750        S  Third   
354         0       3    male  NaN      0      0   7.2250        C  Third   

       who  adult_male deck  embark_town alive  alone  num_missing  
826    man        True  NaN  Southampton    no   True            2  
739    man        True  NaN  Southampton    no   True            2  
495    man        True  NaN    Cherbourg    no   True            2  
223    man        True  NaN  Southampton    no   True            2  
5      man        True  NaN   Queenstown    no   True            2  
388    man        True  NaN   Queenstown    no   True            2  
301    man        True  NaN   Queenstown   yes  False            2  
863  woman       False  NaN  Southampton    no  False            2  
107    man        True  NaN  Southampton   yes   True            2  
354    man        True  NaN    Cherbourg    no   True            2

In [70]:
w = pd.read_csv('../data/weather.csv')

In [71]:
w.head()

id  year  month element  d1    d2    d3  d4    d5  d6 ...   d22   d23  \
0  MX17004  2010      1    tmax NaN   NaN   NaN NaN   NaN NaN ...   NaN   NaN   
1  MX17004  2010      1    tmin NaN   NaN   NaN NaN   NaN NaN ...   NaN   NaN   
2  MX17004  2010      2    tmax NaN  27.3  24.1 NaN   NaN NaN ...   NaN  29.9   
3  MX17004  2010      2    tmin NaN  14.4  14.4 NaN   NaN NaN ...   NaN  10.7   
4  MX17004  2010      3    tmax NaN   NaN   NaN NaN  32.1 NaN ...   NaN   NaN   

   d24  d25  d26  d27  d28  d29   d30  d31  
0  NaN  NaN  NaN  NaN  NaN  NaN  27.8  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  14.5  NaN  
2  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  

[5 rows x 35 columns]

In [74]:
1_000_000 == 1000000

True

In [75]:
1_000_000

1000000

In [76]:
[1, 2, 3, 4, 5,]

[1, 2, 3, 4, 5]

In [77]:
[1,
 2,
 3,
 4,
 5,
]

[1, 2, 3, 4]

In [78]:
def avg_2(x, y):
    return (x + y) / 2

In [79]:
df

a   b
0  10  20
1  20  30
2  30  40

In [82]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [83]:
def avg_2_mod(x, y):
    if(x == 20):
        return np.NaN
    # elif()):
    else:
        return (x + y) / 2

In [84]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [85]:
avg_2_mod(10, 20)

15.0

In [86]:
avg_2_mod(20, 30)

nan

In [87]:
import numpy as np

In [88]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [89]:
df

a   b
0  10  20
1  20  30
2  30  40

In [90]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [91]:
def avg_2_mod(x, y):
    if(x == 20):
        return np.NaN
    # elif()):
    else:
        return (x + y) / 2

avg_2_mod_vec = np.vectorize(avg_2_mod)

In [121]:
@np.vectorize
def v_avg_2_mod(x, y):
    if(x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [107]:
df

a   b
0  10  20
1  20  30
2  30  40

In [108]:
v_avg_2_mod(df['a'], df['b'])

y is 40!


array([15., nan, nan])

In [109]:
import numba

In [117]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if(x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [118]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [119]:
%%timeit
avg_2(df['a'], df['b'])

386 µs ± 95.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [122]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

85.6 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [123]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

10.1 µs ± 836 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
